### ISSUE TITLE
Set Capistrano ruby version in sync with the .rbenv-version.

### ISSUE THREAD

**Issue by grdw** [etrm/keuzehulp#36]
The ruby version [here](https://github.com/etrm/keuzehulp/blob/master/config/deploy.rb#L9) is not the same as [here](https://github.com/etrm/keuzehulp/blob/master/.ruby-version). These two should match up or else the application won't start on the server.

**Comment by ChaelKruip** [comment]
Thanks @grdw for noticing and describing. How much time would it take to do this?

**Comment by grdw** [comment]
2 minutes to change that [single line](https://github.com/etrm/keuzehulp/blob/master/config/deploy.rb#L9) 2.1.1 to 2.1.3 👍 If everything is okay, the server should pick it up and install the correct dependencies.
