### ISSUE TITLE
Can we get (anonymous) user statistics on which attributes are being selected how often?

### ISSUE THREAD

**Issue by ChaelKruip** [etrm/keuzehulp#37]
This would tell us a lot about what people visiting our site are actually looking for in a tool.

@antw @grdw can you give us an idea of how feasible this is?

**Comment by ChaelKruip** [comment]
> @antw @grdw can you give us an idea of how feasible this is?

Ping!

**Comment by grdw** [comment]
We could use [google analytics event tracking](https://developers.google.com/analytics/devguides/collection/analyticsjs/events) for this job. It's very feasible. I have to test it out though, but I don't think it's that hard todo. So perhaps a day or two max is a reasonable guesstimate?

**Comment by grdw** [comment]
@ChaelKruip before this issue, could you be so kind to create a Google analytics account. Maybe it would be great to create one account for keuzehulp, ETM and ETEngine? With an email like: analytics[at]quintel.com

**Comment by ChaelKruip** [comment]
> @ChaelKruip before this issue, could you be so kind to create a Google analytics account.

Can you do this yourself? Or is there payment required?

**Comment by grdw** [comment]
> Can you do this yourself? Or is there payment required?

I can't do this, I'm not the admin of the google account, as far as I can see.

**Comment by grdw** [comment]
Google Analytics account is created! 👍

**Comment by grdw** [comment]
Closed by https://github.com/etrm/keuzehulp/commit/feaa92bcf80025ed5d8ab590af5f2a38645d1c05 and previous x related commits
